# Generated by Django 5.1.6 on 2025-04-28 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cours", "0003_rename_id_cours_idcours"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lesson",
            fields=[
                ("idLesson", models.AutoField(primary_key=True, serialize=False)),
                ("titrLesson", models.CharField(max_length=10)),
                ("contenuLesson", models.TextField()),
                ("niveau", models.IntegerField()),
                ("estTermine", models.BooleanField(default=False)),
                (
                    "idCours",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cours.cours"
                    ),
                ),
            ],
        ),
    ]
