# Generated by Django 5.1.6 on 2025-05-03 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cours", "0003_rename_id_cours_idcours"),
        ("lesson", "0002_rename_idcours_lesson_cours"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="cours",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lessons",
                to="cours.cours",
            ),
        ),
    ]
