# Generated by Django 5.1.6 on 2025-05-14 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lesson", "0003_alter_lesson_cours"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="titrLesson",
            field=models.TextField(),
        ),
    ]
