# Generated by Django 5.1.6 on 2025-05-13 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("progres", "0002_alter_progresutilisateur_niveau"),
    ]

    operations = [
        migrations.AlterField(
            model_name="progresutilisateur",
            name="niveau",
            field=models.IntegerField(default=1),
        ),
    ]
