# Generated by Django 5.1.6 on 2025-05-14 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("progres", "0004_alter_progresutilisateur_niveau"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="progresutilisateur",
            name="estCompleted",
        ),
    ]
