# Generated by Django 5.1.6 on 2025-04-28 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("lesson", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Qcm",
            fields=[
                ("idQcm", models.AutoField(primary_key=True, serialize=False)),
                ("titreQcm", models.CharField(max_length=10)),
                ("scoreMax", models.IntegerField(default=3, editable=False)),
                (
                    "idLesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="lesson.lesson"
                    ),
                ),
            ],
        ),
    ]
