# Generated by Django 5.1.6 on 2025-04-29 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("qcm", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="qcm",
            old_name="idLesson",
            new_name="lesson",
        ),
    ]
