# Generated by Django 5.1.6 on 2025-05-08 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lesson", "0003_alter_lesson_cours"),
        ("qcm", "0002_rename_idlesson_qcm_lesson"),
    ]

    operations = [
        migrations.AlterField(
            model_name="qcm",
            name="lesson",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="qcm",
                to="lesson.lesson",
            ),
        ),
        migrations.AlterField(
            model_name="qcm",
            name="titreQcm",
            field=models.TextField(),
        ),
    ]
