# Generated by Django 5.1.6 on 2025-05-08 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("qcm", "0003_alter_qcm_lesson_alter_qcm_titreqcm"),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                ("idQuestion", models.AutoField(primary_key=True, serialize=False)),
                ("texte", models.TextField()),
                (
                    "qcm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="qcm.qcm",
                    ),
                ),
            ],
        ),
    ]
