# Generated by Django 5.1.6 on 2025-04-28 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("qcm", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reponse",
            fields=[
                ("idReponse", models.AutoField(primary_key=True, serialize=False)),
                ("rep", models.CharField(max_length=10)),
                ("natureRep", models.BooleanField()),
                (
                    "idQcm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="qcm.qcm"
                    ),
                ),
            ],
        ),
    ]
