# Generated by Django 5.1.6 on 2025-04-29 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reponse", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reponse",
            old_name="idQcm",
            new_name="qcm",
        ),
    ]
