# Generated by Django 5.1.6 on 2025-05-08 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qcm", "0003_alter_qcm_lesson_alter_qcm_titreqcm"),
        ("reponse", "0002_rename_idqcm_reponse_qcm"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reponse",
            name="qcm",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="qcm.qcm",
            ),
        ),
        migrations.AlterField(
            model_name="reponse",
            name="rep",
            field=models.TextField(),
        ),
    ]
