# Generated by Django 5.1.6 on 2025-05-08 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("question", "0001_initial"),
        ("reponse", "0003_alter_reponse_qcm_alter_reponse_rep"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reponse",
            name="qcm",
        ),
        migrations.AddField(
            model_name="reponse",
            name="question",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reponses",
                to="question.question",
            ),
            preserve_default=False,
        ),
    ]
