# Generated by Django 5.1.6 on 2025-04-24 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cours",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titreCours", models.CharField(max_length=20)),
                ("descriptionCours", models.TextField()),
                ("imageCours", models.CharField(max_length=250)),
            ],
        ),
    ]
