# Generated by Django 5.1.6 on 2025-04-25 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cours", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cours",
            name="nombreNiveau",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="cours",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
