# Generated by Django 5.1.6 on 2025-04-25 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cours", "0002_cours_nombreniveau_alter_cours_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cours",
            old_name="id",
            new_name="idCours",
        ),
    ]
